######################################################################################
##############      Tomcats to Remote machie      ####################################
######################################################################################
####### Step 1. Copy tarball to remote machine                                       #
####### Step 2. Extract the Tomcat                                                   #
####### Step 3. Create checksum256 from tarball and store it into checksumDB file    #
######################################################################################
- hosts: all
  roles:
   #TODO NO Download of tarball. Just give path of tarball. THANKS!
   - {role: tomcat,  tarUrl: "https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.10/bin/apache-tomcat-7.0.10.tar.gz"}
   - {role: tomcat,  tarUrl: "https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.92/bin/apache-tomcat-7.0.92.tar.gz"}
   - {role: tomcat,  tarUrl: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.21/bin/apache-tomcat-8.0.21.tar.gz"}
#   - {role: tomcat, tarTempName: "IamTarBall_DeleteMe_7065", tarUrl: "apache-tomcat-7.0.65.tar.gz"}
#   - {role: tomcat, tarTempName: "IamTarBall_DeleteMe_7082", tarUrl: "apache-tomcat-7.0.82.tar.gz"}
#   - {role: tomcat, tarTempName: "IamTarBall_DeleteMe_7092", tarUrl: "apache-tomcat-7.0.92.tar.gz"}
#   - {role: tomcat, tarTempName: "IamTarBall_DeleteMe_8020", tarUrl: "apache-tomcat-8.0.20.tar.gz"}
#   - {role: tomcat, tarTempName: "IamTarBall_DeleteMe_8048", tarUrl: "apache-tomcat-8.0.48.tar.gz"}
#   - {role: tomcat, tarTempName: "IamTarBall_DeleteMe_8051", tarUrl: "apache-tomcat-8.0.51.tar.gz"}
#   - {role: tomcat, tarTempName: "IamTarBall_DeleteMe_8053", tarUrl: "apache-tomcat-8.0.53.tar.gz"}
#   - {role: tomcat, tarTempName: "IamTarBall_DeleteMe_858", tarUrl: "apache-tomcat-8.5.8.tar.gz"}
#   - {role: tomcat, tarTempName: "IamTarBall_DeleteMe_8535", tarUrl: "apache-tomcat-8.5.35.tar.gz"}
